global using AutoFixture;
global using EasyTypeParsing.Tests.Utilities;
global using FluentAssertions;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using System;
global using System.Globalization;
global using System.Numerics;
global using ToolBX.EasyTypeParsing;
global using ToolBX.Eloquentest;
